const menuList = [
    {
        "id": 1,
        "parentId": -1,
        "children": [],
        "icon": null,
        "name": "首页",
        "url": '/home',
        "spread": false,
        "path": null,
        "component": null,
        "authority": null,
        "redirect": null,
        "code": null,
        "type": null,
        "label": "首页"
    },
    {
        "id": 2,
        "parentId": -1,
        "children": [
            {
                "id": 3,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "按钮",
                "url": '/ui/buttons',
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "按钮"
            },
            {
                "id": 4,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "弹框",
                "url": "/ui/modals",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "弹框"
            },
            {
                "id": 5,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "Loading",
                "url": "/ui/loadings",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "Loading"
            },
            {
                "id": 6,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "通知提醒",
                "url": "/ui/notification",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "通知提醒"
            },
            {
                "id": 7,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "全局Message",
                "url": "/ui/messages",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "全局Message"
            },
            {
                "id": 8,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "Tab页签",
                "url": "/ui/tabs",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "Tab页签"
            },
            {
                "id": 9,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "图片画廊",
                "url": "/ui/gallery",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "图片画廊"
            },
            {
                "id": 10,
                "parentId": 2,
                "children": [],
                "icon": null,
                "name": "轮播图",
                "url": "/ui/carousel",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "轮播图"
            }
        ],
        "icon": null,
        "name": "UI",
        "url": '/ui',
        "spread": false,
        "path": null,
        "component": null,
        "authority": null,
        "redirect": null,
        "code": null,
        "type": null,
        "label": "UI"
    },
    {
        "id": 11,
        "parentId": -1,
        "children": [
            {
                "id": 12,
                "parentId": 11,
                "children": [],
                "icon": null,
                "name": "登录",
                "url": "/form/login",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "登录"
            },
            {
                "id": 13,
                "parentId": 11,
                "children": [],
                "icon": null,
                "name": "注册",
                "url": "/form/reg",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "注册"
            }
        ],
        "icon": null,
        "name": "表单",
        "url": "/form",
        "spread": false,
        "path": null,
        "component": null,
        "authority": null,
        "redirect": null,
        "code": null,
        "type": null,
        "label": "表单"
    },
    {
        "id": 14,
        "parentId": -1,
        "children": [
            {
                "id": 15,
                "parentId": 14,
                "children": [],
                "icon": null,
                "name": "基础表格",
                "url": "/table/basic",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "基础表格"
            },
            {
                "id": 16,
                "parentId": 14,
                "children": [],
                "icon": null,
                "name": "高级表格",
                "url": "/table/high",
                "spread": false,
                "path": null,
                "component": null,
                "authority": null,
                "redirect": null,
                "code": null,
                "type": null,
                "label": "高级表格"
            }
        ],
        "icon": null,
        "name": "表格",
        "url": "/table",
        "spread": false,
        "path": null,
        "component": null,
        "authority": null,
        "redirect": null,
        "code": null,
        "type": null,
        "label": "表格"
    }
];
export default menuList;