
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#    instance:
#      hostname: hostname
spring:
  application:
    name: zuul
  redis:
    database: 9
    host: 127.0.0.1
    jedis:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 50
    timeout: 10000
zuul:
  routes:
    myproject:
      path: /web/**
      serviceId: web
      sensitiveHeaders:
      #client: /myproject/**
  ignored-patterns:
    - /myproject/testIgnoreList
    - /client/testIgnoreList
  sensitive-headers:
server:
  port: 7001
  #-/**/
